/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MinhasViagensRouteImport } from './routes/minhas-viagens'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as VoosRouteImport } from './routes/voos'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as DestinosIndexRouteImport } from './routes/destinos.index'
import { Route as DestinosSlugRouteImport } from './routes/destinos.$slug'
import { Route as HoteisIndexRouteImport } from './routes/hoteis.index'
import { Route as HoteisSlugRouteImport } from './routes/hoteis.$slug'
import { Route as PacotesIndexRouteImport } from './routes/pacotes.index'
import { Route as PacotesSlugRouteImport } from './routes/pacotes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasViagensRoute = MinhasViagensRouteImport.update({
  id: '/minhas-viagens',
  path: '/minhas-viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const VoosRoute = VoosRouteImport.update({
  id: '/voos',
  path: '/voos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosIndexRoute = DestinosIndexRouteImport.update({
  id: '/destinos/',
  path: '/destinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosSlugRoute = DestinosSlugRouteImport.update({
  id: '/destinos/$slug',
  path: '/destinos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HoteisIndexRoute = HoteisIndexRouteImport.update({
  id: '/hoteis/',
  path: '/hoteis/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoteisSlugRoute = HoteisSlugRouteImport.update({
  id: '/hoteis/$slug',
  path: '/hoteis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PacotesIndexRoute = PacotesIndexRouteImport.update({
  id: '/pacotes/',
  path: '/pacotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacotesSlugRoute = PacotesSlugRouteImport.update({
  id: '/pacotes/$slug',
  path: '/pacotes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/entrar': typeof EntrarRoute
  '/minhas-viagens': typeof MinhasViagensRoute
  '/ofertas': typeof OfertasRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/voos': typeof VoosRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/hoteis/$slug': typeof HoteisSlugRoute
  '/pacotes/$slug': typeof PacotesSlugRoute
  '/destinos/': typeof DestinosIndexRoute
  '/hoteis/': typeof HoteisIndexRoute
  '/pacotes/': typeof PacotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/entrar': typeof EntrarRoute
  '/minhas-viagens': typeof MinhasViagensRoute
  '/ofertas': typeof OfertasRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/voos': typeof VoosRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/hoteis/$slug': typeof HoteisSlugRoute
  '/pacotes/$slug': typeof PacotesSlugRoute
  '/destinos': typeof DestinosIndexRoute
  '/hoteis': typeof HoteisIndexRoute
  '/pacotes': typeof PacotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/busca': typeof BuscaRoute
  '/entrar': typeof EntrarRoute
  '/minhas-viagens': typeof MinhasViagensRoute
  '/ofertas': typeof OfertasRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/voos': typeof VoosRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/hoteis/$slug': typeof HoteisSlugRoute
  '/pacotes/$slug': typeof PacotesSlugRoute
  '/destinos/': typeof DestinosIndexRoute
  '/hoteis/': typeof HoteisIndexRoute
  '/pacotes/': typeof PacotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/busca'
    | '/entrar'
    | '/minhas-viagens'
    | '/ofertas'
    | '/sobre'
    | '/suporte'
    | '/voos'
    | '/checkout/$slug'
    | '/destinos/$slug'
    | '/hoteis/$slug'
    | '/pacotes/$slug'
    | '/destinos/'
    | '/hoteis/'
    | '/pacotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/busca'
    | '/entrar'
    | '/minhas-viagens'
    | '/ofertas'
    | '/sobre'
    | '/suporte'
    | '/voos'
    | '/checkout/$slug'
    | '/destinos/$slug'
    | '/hoteis/$slug'
    | '/pacotes/$slug'
    | '/destinos'
    | '/hoteis'
    | '/pacotes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/busca'
    | '/entrar'
    | '/minhas-viagens'
    | '/ofertas'
    | '/sobre'
    | '/suporte'
    | '/voos'
    | '/checkout/$slug'
    | '/destinos/$slug'
    | '/hoteis/$slug'
    | '/pacotes/$slug'
    | '/destinos/'
    | '/hoteis/'
    | '/pacotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscaRoute: typeof BuscaRoute
  EntrarRoute: typeof EntrarRoute
  MinhasViagensRoute: typeof MinhasViagensRoute
  OfertasRoute: typeof OfertasRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  VoosRoute: typeof VoosRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  DestinosSlugRoute: typeof DestinosSlugRoute
  HoteisSlugRoute: typeof HoteisSlugRoute
  PacotesSlugRoute: typeof PacotesSlugRoute
  DestinosIndexRoute: typeof DestinosIndexRoute
  HoteisIndexRoute: typeof HoteisIndexRoute
  PacotesIndexRoute: typeof PacotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-viagens': {
      id: '/minhas-viagens'
      path: '/minhas-viagens'
      fullPath: '/minhas-viagens'
      preLoaderRoute: typeof MinhasViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voos': {
      id: '/voos'
      path: '/voos'
      fullPath: '/voos'
      preLoaderRoute: typeof VoosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos/': {
      id: '/destinos/'
      path: '/destinos'
      fullPath: '/destinos/'
      preLoaderRoute: typeof DestinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos/$slug': {
      id: '/destinos/$slug'
      path: '/destinos/$slug'
      fullPath: '/destinos/$slug'
      preLoaderRoute: typeof DestinosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteis/': {
      id: '/hoteis/'
      path: '/hoteis'
      fullPath: '/hoteis/'
      preLoaderRoute: typeof HoteisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteis/$slug': {
      id: '/hoteis/$slug'
      path: '/hoteis/$slug'
      fullPath: '/hoteis/$slug'
      preLoaderRoute: typeof HoteisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacotes/': {
      id: '/pacotes/'
      path: '/pacotes'
      fullPath: '/pacotes/'
      preLoaderRoute: typeof PacotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacotes/$slug': {
      id: '/pacotes/$slug'
      path: '/pacotes/$slug'
      fullPath: '/pacotes/$slug'
      preLoaderRoute: typeof PacotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscaRoute: BuscaRoute,
  EntrarRoute: EntrarRoute,
  MinhasViagensRoute: MinhasViagensRoute,
  OfertasRoute: OfertasRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  VoosRoute: VoosRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  DestinosSlugRoute: DestinosSlugRoute,
  HoteisSlugRoute: HoteisSlugRoute,
  PacotesSlugRoute: PacotesSlugRoute,
  DestinosIndexRoute: DestinosIndexRoute,
  HoteisIndexRoute: HoteisIndexRoute,
  PacotesIndexRoute: PacotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
